### ISSUE TITLE
Add offset parameter to PortalEntry

### ISSUE THREAD

**Issue by Quijx** [rrousselGit/flutter_portal#13]
**Is your feature request related to a problem? Please describe.**
If it is needed to offset the overlayed widget by a fixed amount, one way to do that currently is with a `Transform` widget. However there, one might run into issues with the limitations described in https://github.com/flutter/flutter/issues/27587.
There are ways to circumvent this, for example by making the overlayed widget bigger and positioning the child within it with an offset. (For example by using a `Stack`.)

**Describe the solution you'd like**
However it would be more convenient to have an `offset` parameter in the `PortalEntry` that just offsets the `portal` child by a fixed amount.

**Comment by rrousselGit** [comment]
You can use a Padding

**Comment by Quijx** [comment]
True. It didn't occur to me :grin: That would probably work for most cases. However for example when `portalAnchor` is `Alignment.center`, the applied offset is only half of the padding. That might be a bit confusing at first glance.
Or consider a case where the offset is animated and changes sign. Then, either the left or right (/top or bottom) padding has to be used depending on the sign. 
Another case would be with these selection handles in text fields. Here the offset is semantically not a padding, so using a `Padding` widget would be a bit of a hack in my opinion.
Therefore I think an `offset` parameter would still be useful, even if not absolutely necessary.

**Comment by ruskakimov** [comment]
AFAIK padding doesn't work for negative offsets

**Comment by fzyzcjy** [comment]
Hi, https://github.com/rrousselGit/flutter_portal/pull/44 is merged. Could you please check whether this issue is resolved :)

**Comment by Quijx** [comment]
@fzyzcjy Looking at the API it does seem like the `Aligned` anchor can do exactly that. However I tried running it using a git dependency but I'm getting the following error:
```
ERROR: ../../../../../../.pub-cache/git/flutter_portal-9b9463cbc7a660c9a2e3a614a0ce83aa623cb8ba/lib/src/custom_follower.dart:300:52: Error: The getter 'leader' isn't defined for the class 'LayerLink'.
ERROR:  - 'LayerLink' is from 'package:flutter/src/rendering/layer.dart' ('../../../../../../.fvm/versions/2.10.2/packages/flutter/lib/src/rendering/layer.dart').
ERROR: Try correcting the name to the name of an existing getter, or defining a getter or field named 'leader'.
ERROR:     final linkedOffset = linkedOffsetCallback(link.leader!.offset);
ERROR:                                                    ^^^^^^
ERROR: ../../../../../../.pub-cache/git/flutter_portal-9b9463cbc7a660c9a2e3a614a0ce83aa623cb8ba/lib/src/custom_follower.dart:308:14: Error: The getter 'leader' isn't defined for the class 'LayerLink'.
ERROR:  - 'LayerLink' is from 'package:flutter/src/rendering/layer.dart' ('../../../../../../.fvm/versions/2.10.2/packages/flutter/lib/src/rendering/layer.dart').
ERROR: Try correcting the name to the name of an existing getter, or defining a getter or field named 'leader'.
ERROR:     if (link.leader == null) {
ERROR:              ^^^^^^
ERROR: ../../../../../../.pub-cache/git/flutter_portal-9b9463cbc7a660c9a2e3a614a0ce83aa623cb8ba/lib/src/custom_follower.dart:370:25: Error: The getter 'leader' isn't defined for the class 'LayerLink'.
ERROR:  - 'LayerLink' is from 'package:flutter/src/rendering/layer.dart' ('../../../../../../.fvm/versions/2.10.2/packages/flutter/lib/src/rendering/layer.dart').
ERROR: Try correcting the name to the name of an existing getter, or defining a getter or field named 'leader'.
ERROR:     final leader = link.leader;
ERROR:                         ^^^^^^
ERROR: ../../../../../../.pub-cache/git/flutter_portal-9b9463cbc7a660c9a2e3a614a0ce83aa623cb8ba/lib/src/custom_follower.dart:420:14: Error: The getter 'leader' isn't defined for the class 'LayerLink'.
ERROR:  - 'LayerLink' is from 'package:flutter/src/rendering/layer.dart' ('../../../../../../.fvm/versions/2.10.2/packages/flutter/lib/src/rendering/layer.dart').
ERROR: Try correcting the name to the name of an existing getter, or defining a getter or field named 'leader'.
ERROR:     if (link.leader == null) {
ERROR:              ^^^^^^
Exception: Build process failed
```
I am using Flutter 2.10.2.

**Comment by fzyzcjy** [comment]
@Quijx I have fixed it. Could you please try the master of this repo again?

**Comment by fzyzcjy** [comment]
@Quijx Interesting... Could you please share a minimal reproducible sample, and provide your flutter version?

**Comment by Quijx** [comment]
@fzyzcjy I am having trouble reproducing the bug in an isolated example, but it does only occur with the `Filled` `Anchor`. Everything works fine with the `Aligned` `Anchor`. I have also tried the offset parameter on the `Aligned` anchor and it does what I expected :) So I'm closing this issue, since this is what it is about.

The bug happened both on Flutter 2.10.2 and 2.10.3. I will update you if I find the cause of the bug.
While experimenting I found another possible problem though. Take this app for example:
```dart
Scaffold(
      appBar: AppBar(
        title: Text('flutter_portal Bug'),
      ),
      body: Portal(
        child: Column(
          children: [
            PortalTarget(
              portalFollower: Container(
                color: Colors.green.withOpacity(0.5),
              ),
              child: Container(
                color: Colors.red,
                width: 24,
                height: 24,
              ),
            ),
          ],
        ),
      ),
    );
```
If you open this in flutter desktop and resize only the height of the window to be bigger, the green box will not expand to the full height, and a white area will appear under it. Once you resize the width, it jumps to fill the whole area again. Without the `Column`, this works fine. Maybe the problem is related?

**Comment by fzyzcjy** [comment]
> I will update you if I find the cause of the bug.

Or if you find a reproducible sample (even without finding the cause) :)

> If you open this in flutter desktop and resize only the height of the window to be bigger, the green box will not expand to the full height, and a white area will appear under it. Once you resize the width, it jumps to fill the whole area again. Without the Column, this works fine. Maybe the problem is related?

Interesting... Sounds like improper rebuilding/relayouting issues?
Could you please make a separate issue for this, such that people are easier to see and discuss it

**Comment by Quijx** [comment]
Sure. Hopefully later today I'll find some time to make the issue.

**Comment by Quijx** [comment]
@fzyzcjy So... Today i got around to creating the issue: #53
