### ISSUE TITLE
Tooltip is painted behind portal

### ISSUE THREAD

**Issue by ruskakimov** [rrousselGit/flutter_portal#18]
**Describe the bug**
Icon tooltip is painted behind portal material.

![image](https://user-images.githubusercontent.com/5536948/97825155-e1c23380-1cf8-11eb-8295-6aa9ff0c9f84.png)

**To Reproduce**
```dart
import 'package:flutter/material.dart';
import 'package:flutter_portal/flutter_portal.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Portal(
      child: MaterialApp(
        home: Scaffold(
          body: PortalEntry(
            visible: true,
            childAnchor: Alignment.center,
            portalAnchor: Alignment.center,
            portal: Material(
              color: Colors.white,
              child: SizedBox(
                width: 80,
                height: 80,
                child: IconButton(
                  icon: Icon(Icons.hot_tub),
                  tooltip: 'This tooltip is behind Material above',
                  onPressed: () {},
                ),
              ),
            ),
            child: Container(
              color: Colors.grey,
            ),
          ),
        ),
      ),
    );
  }
}
```

**Expected behavior**
Icon tooltip should be rendered on top.

**Comment by ruskakimov** [comment]
![image](https://user-images.githubusercontent.com/5536948/97825600-1f738c00-1cfa-11eb-8c08-24bd145a148e.png)
Fixed when `Portal` is placed directly above `Scaffold` instead of `MaterialApp`. 😄

**Comment by ruskakimov** [comment]
Perhaps can be mentioned in docs? @rrousselGit

**Comment by rrousselGit** [comment]
This is expected, as you placed `Portal` above by Navigator/MaterialApp.
Doing so means your portals will be displayed above _everything_, which includes "stay visible when changing routes".
