### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by winwisely99** [rrousselGit/flutter_portal#2]
The docs in the readme are top notch - great job.

Seriously looking at using this but wondring if it uses the new Flutter Navigator 2.0 API.
I read that google are going to support the old API also.

Just trying to work out how the puzzle fits together for our roadmap and if we shoudl use Portal.

One thing we find is that Modal Overlays dont always work well on Flutter Web for example.

**Comment by rrousselGit** [comment]
This is made from scratch and doesn't rely on navigator at all

**Comment by winwisely99** [comment]
Ok thanks for letting me know.

Will have to try it out.
