### ISSUE TITLE
Please document how hit-testing works

### ISSUE THREAD

**Issue by derolf** [rrousselGit/flutter_portal#22]
I tried to use flutter_portal to render "stickers" on top of "Cards", like this:

```
############
#          #
# Foo      #
# 1234   /-------------|    
#       <    Important |
#        \-------------|   
#          #
#          #
############
```

However, tapping on "Important" isn't able to receive tap gestures. 

UPDATE: It looks like the hittest is happening vertically below the sticker?! If I tap like 100 pixels below "Important", it's getting tapped.

UPDATE: Looks like `Portal` has to be fullscreen?

**Comment by fzyzcjy** [comment]
IMHO hit testing only happens within the boundary of `Portal`, since the implementation of this library is that, the PortalEntry's portals behave as if they are children of Portal.
