### ISSUE TITLE
Navigator pop after entry click?

### ISSUE THREAD

**Issue by brunodmn** [rrousselGit/flutter_portal#37]
**Describe the bug**
After click, all current page is popped instead of only portal. I am doing something wrong?

**To Reproduce**
Reproduced code is in your own example [contextual_menu](https://github.com/rrousselGit/flutter_portal/blob/master/example/lib/contextual_menu.dart). After you click on the first or second item of 'show menu' button, screen is disposed.

**Expected behavior**
Only the portal menu should be closed.

**Comment by fzyzcjy** [comment]
I guess portal is not something like a "page" or "dialog", so navigator is not aware of it.

**Comment by fzyzcjy** [comment]
You can use `WillPopScope` to do arbitrary operations, including "hide the portal entry".
