### ISSUE TITLE
Updating visible for nested portals.

### ISSUE THREAD

**Issue by aloisdeniel** [rrousselGit/flutter_portal#4]
When  nesting two portal entries and defining the same `visible` for both , only the inner portal is updated.

```dart
PortalEntry(
      visible: isOpen,
      child: PortalEntry(
        visible: isOpen,
        ...
      ),
      ...
  );
```

**Comment by rrousselGit** [comment]
@aloisdeniel Did you try the branch I gave you? 

https://github.com/rrousselGit/flutter_portal/tree/rework

This branch fixes the problem (in theory).

**Comment by nioncode** [comment]
Fwiw, I tried the branch and nesting `PortalEntries` seems to work fine based on a quick test (see example in #6). Will this new branch become the default or is there anything blocking this?

**Comment by rrousselGit** [comment]
I'll merge it in a bit
