### ISSUE TITLE
Using anchoring together with Positioned.fill

### ISSUE THREAD

**Issue by nioncode** [rrousselGit/flutter_portal#6]
Is it possible to create a `PortalEntry` that has the following two behaviors at the same time:

* full screen `GestureDetector` to dismiss the current `PortalEntry` whenever you tap outside of it (like your date picker example)
* anchoring the actual overlay `Widget` to the child (like in the contextual menu example)

I tried various things, even using two `PortalEntries` at the same time (one full screen for the `GestureDetector` and another with just the `Widget` that gets anchored to the child), but couldn't get it to work and am wondering whether this is actually possible with the current design.

Previously, I implemented my Overlays by hand with a `Stack`, but then I failed to position the overlay correctly, because I don't have the size of the actual overlay when it comes to positioning it relative to the target with `CompositedTransformFollower`. I hoped your library would be a solution to this, but at the moment I am failing to achieve the points above.

**Comment by rrousselGit** [comment]
Not for now, but you can use two Portal to achieve the same result

**Comment by nioncode** [comment]
Do you mean two Portals or two PortalEntries? I tried with two entries and then had to use your `rework` branch (because of #4), but now it looks like everything works fine with the following code.
Is this what you had in mind?

```dart
class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool visible = false;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Portal(
        child: Center(
          child: PortalEntry(
            visible: visible,
            portal: Container(
              child: GestureDetector(
                onTap: () {
                  print('dismissed');
                  setState(() {
                    visible = false;
                  });
                },
              ),
            ),
            child: PortalEntry(
              visible: visible,
              portalAnchor: Alignment.bottomCenter,
              childAnchor: Alignment.topCenter,
              portal: RaisedButton(
                child: Text('Close'),
                onPressed: () {
                  print('closed');
                  setState(() {
                    visible = false;
                  });
                },
              ),
              child: RaisedButton(
                child: Text('Open Overlay'),
                onPressed: () {
                  setState(() {
                    print('toggling overlay');
                    visible = !visible;
                  });
                },
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by rrousselGit** [comment]
This is what I was thinking of, yes

**Comment by misterfourtytwo** [comment]
@rrousselGit is there any way to get global coordinates of anchor point inside portal field of PortalEntry?
i'm trying to position my popup hint based on the position of a child, so it will be fully drawn on the screen for both appbar and bottomnavbar, while the Alignment is like really cool, is there a way to specify it based on child location?
