### ISSUE TITLE
Necessity to provide a top level Portal

### ISSUE THREAD

**Issue by nioncode** [rrousselGit/flutter_portal#7]
I was thinking about replacing my current implementation of a context menu based on `OverlayEntry` with `PortalEntry`.

Currently, I have a widget tree like this:
> MaterialApp -> Homescreen -> Scaffold -> CustomScrollView -> Column -> Row -> CustomButton

`CustomButton` is where I currently implemented showing the `OverlayEntry`. When switching to using `PortalEntry`, I have to wrap some outer widget like `CustomScrollView` with `Portal`.
If I only use `Portal` to wrap `CustomButton`'s `build` method, full screen overlays are offset to the bottom right (i.e. they do not fill the screen anymore) and hit testing on the `Portal` does not seem to work (at least when the `Portal` is positioned to the top left of `CustomButton`).

Is it possible to use `PortalEntry` without wrapping the upper widget tree in a `Portal`? It feels weird to wrap the outer widgets, since the choice of using `PortalEntry` over `OverlayEntry` should be an implementation detail of my `CustomButton` widget and not affect the parent widgets. Could we maybe add a variable like `useRootOverlay` that always assumes a full screen Portal at 0x0 (while still allowing anchoring it to its child) or maybe even do that as default if no parent `Portal` is specified?

**Comment by rrousselGit** [comment]
This is not feasible.
This package is not built on the top of Overlay, but is a reimplementation of Overlay

They are not compatible with each others.

**Comment by nioncode** [comment]
Thanks, so I assume the only reasonable way to use portals is to wrap the entire widget tree, since in general we can not know where the portal might end up on screen and if it is somewhere outside its parent's bounds than hit testing does not work anymore.

Is this correct? This would be great to point out in the docs then, if there is not really a reason to NOT wrap the entire tree in some cases.

**Comment by rrousselGit** [comment]
You may want to place the Portal at different locations to change the clip behavior

**Comment by nioncode** [comment]
Closing this, since PortalEntry works entirely different from OverlayEntry and thus needs the Portal somewhere higher in the widget tree.
