### ISSUE TITLE
Support for Positioned and AnimatedPositioned

### ISSUE THREAD

**Issue by grinder15** [rrousselGit/flutter_portal#8]
The following code gives me `Incorrect use of ParentDataWidget` exception
```
PortalEntry(
     portal: Positioned(
          top: 24.0,
          left: 16.0,
          child: Card(
               child: Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Text("Hi, I'm portal."),
               ),
           ),
     ),
     child: Text(
          'Example',
     ),
)
```
same goes with AnimatedPositioned

I think it's better to have `PortalEntry`  the same use case as the `OverlayEntry` where `Positioned` and `AnimatedPositioned` works.

btw, nice package, looking forward to further development. 👍

**Comment by rrousselGit** [comment]
What would be the benefit over:

PortalEntry(
  portal: Stack(
    childre: [...],
 )
)

 ?


Overlay uses Stack internally so it makes sense. But Portal doesn't
