### ISSUE TITLE
README.md has wrong version

### ISSUE THREAD

**Issue by dan-gph** [rrousselGit/flutter_portal#9]
The Installation section of README.md specifies `flutter_portal: ^0.0.1`, but it should be `flutter_portal: ^0.1.0`.

The problem is that the 0.0.1 versions no longer build, and Upgrade Packages won't automatically upgrade ^0.0.1 to 0.1.0. That means that the initial experience that people have with this package will be disappointing.

**Comment by rrousselGit** [comment]
Thanks for the report!
